// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldCupScoreboard.Persistence;

#nullable disable

namespace WorldCupScoreboard.Persistence.Migrations
{
    [DbContext(typeof(ScoreboardDbContext))]
    partial class ScoreboardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("WorldCupScoreboard.Match", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("WorldCupScoreboard.Match", b =>
                {
                    b.OwnsOne("WorldCupScoreboard.Team", "AwayTeam", b1 =>
                        {
                            b1.Property<int>("MatchId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("AwayTeamName");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER")
                                .HasColumnName("AwayTeamScore");

                            b1.HasKey("MatchId");

                            b1.ToTable("Matches");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.OwnsOne("WorldCupScoreboard.Team", "HomeTeam", b1 =>
                        {
                            b1.Property<int>("MatchId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("HomeTeamName");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER")
                                .HasColumnName("HomeTeamScore");

                            b1.HasKey("MatchId");

                            b1.ToTable("Matches");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.Navigation("AwayTeam")
                        .IsRequired();

                    b.Navigation("HomeTeam")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
